import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import "./globals.css";
import Provider from './provider';
import { Toaster } from '@/components/ui/sonner';

const AppFont=Arimo({subsets:["latin"]})

export const metadata: Metadata = {
  title: "Ai Video Generator App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
       className={AppFont.className} 
       >
        <Provider>
          {children}
          <Toaster position='top-center' richColors />
        </Provider>
        
      </body>
    </html> 
    </ClerkProvider>
     );
}
