import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import "./globals.css";

const AppFont=Arimo({subsets:["latin"]})

export const metadata: Metadata = {
  title: "Ai Video Generator App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={AppFont.className}
      >
        {children}
      </body>
    </html>
  );
}
